List<String> id = ['0', '1', '2', '3', '4'];

List name = [
  'Mercado Alfa II',
  'Mini Extra - Conselheiro',
  'DIA Supermercado',
  'Pão de Açúcar - Santos',
  'Makro Atacadista - Santos',
];

List address = [
  'Av. Conselheiro Rodrigues Alves, 400',
  'Av. Conselheiro Nébias, 417',
  'R. Carvalho de Mendonça, 116',
  'Av. Conselheiro Nébias, 568',
  'Av. Nossa Senhora de Fátima, 1440',
];

Map items = {
  '0': [
    ['acucar', 'corredor abc', 'assets/piso1-A.png'],
    ['agua mineral', 'corredor abc', 'assets/piso1-B.png'],
    ['aguardentes', 'corredor abc', 'assets/piso1-C.png'],
    ['aguas sanitarias', 'corredor abc', 'assets/piso1-D.png'],
    ['alvejantes e tira manchas', 'corredor abc', 'assets/piso1-E.png'],
    ['amaciantes', 'corredor abc', 'assets/piso1-A.png'],
    ['aperitivos', 'corredor abc', 'assets/piso1-B.png'],
    ['aperitivos e petiscos', 'corredor abc', 'assets/piso1-C.png'],
    ['armarinho', 'corredor abc', 'assets/piso1-D.png'],
    ['arroz', 'corredor abc', 'assets/piso1-E.png'],
    ['artigos de couro', 'corredor abc', 'assets/piso1-A.png'],
    ['artigos de vertuario', 'corredor abc', 'assets/piso1-B.png'],
    ['artigos esportivos', 'corredor abc', 'assets/piso1-C.png'],
    ['artigos fotograficos', 'corredor abc', 'assets/piso1-D.png'],
    ['artigos para animais', 'corredor abc', 'assets/piso1-E.png'],
    ['artigos para bar', 'corredor abc', 'assets/piso1-A.png'],
    ['artigos para bebe', 'corredor abc', 'assets/piso1-B.png'],
    ['artigos para festa', 'corredor abc', 'assets/piso1-C.png'],
    ['artigos para fumantes', 'corredor abc', 'assets/piso1-D.png'],
    ['artigos para mesa', 'corredor abc', 'assets/piso1-E.png'],
    ['artigos religiosos', 'corredor abc', 'assets/piso1-A.png'],
    ['aves cong/resfriadas', 'corredor abc', 'assets/piso1-B.png'],
    ['aves congeladas e resfriadas', 'corredor abc', 'assets/piso1-C.png'],
    ['azeites e oleos compostos', 'corredor abc', 'assets/piso1-D.png'],
    ['bacalhau', 'corredor abc', 'assets/piso1-E.png'],
    ['banheiro e lavanderia', 'corredor abc', 'assets/piso1-A.png'],
    ['bazar sr', 'corredor abc', 'assets/piso1-B.png'],
    ['bicicleta colab', 'corredor abc', 'assets/piso1-C.png'],
    ['biscoitos', 'corredor abc', 'assets/piso1-D.png'],
    ['bomboniere', 'corredor abc', 'assets/piso1-E.png'],
    ['brindes', 'corredor abc', 'assets/piso1-A.png'],
    ['brinquedos', 'corredor abc', 'assets/piso1-B.png'],
    ['cafes', 'corredor abc', 'assets/piso1-C.png'],
    ['cafeteiras', 'corredor abc', 'assets/piso1-D.png'],
    ['calcados', 'corredor abc', 'assets/piso1-E.png'],
    ['cama/mesa/banho', 'corredor abc', 'assets/piso1-A.png'],
    ['camping/churrasco', 'corredor abc', 'assets/piso1-B.png'],
    ['caprinos', 'corredor abc', 'assets/piso1-C.png'],
    ['carne de cordeiro', 'corredor abc', 'assets/piso1-D.png'],
    ['carnes enlatadas', 'corredor abc', 'assets/piso1-E.png'],
    ['celular', 'corredor abc', 'assets/piso1-A.png'],
    ['ceras,polidores e alcool' 'corredor abc', 'assets/piso1-B.png']
  ],
  '1': [
    ['cervejas', 'gondola 123', 'assets/piso1-A.png'],
    ['cesta basica', 'gondola 123', 'assets/piso1-B.png'],
    ['champagnes e espumantes', 'gondola 123', 'assets/piso1-C.png'],
    ['chas', 'gondola 123', 'assets/piso1-D.png'],
    ['chips', 'gondola 123', 'assets/piso1-E.png'],
    ['chopperia', 'gondola 123', 'assets/piso1-A.png'],
    ['compotas', 'gondola 123', 'assets/piso1-B.png'],
    ['condicionadores', 'gondola 123', 'assets/piso1-C.png'],
    ['condimentos', 'gondola 123', 'assets/piso1-D.png'],
    ['conhaques', 'gondola 123', 'assets/piso1-E.png'],
    ['conjunto p/chimarrao', 'gondola 123', 'assets/piso1-A.png'],
    ['copa e cozinha', 'gondola 123', 'assets/piso1-B.png'],
    ['creme de leite', 'gondola 123', 'assets/piso1-C.png'],
    ['creme de queijo', 'gondola 123', 'assets/piso1-D.png'],
    ['dbcv', 'gondola 123', 'assets/piso1-E.png'],
    ['derivados de frutas', 'gondola 123', 'assets/piso1-A.png'],
    ['descartaveis', 'gondola 123', 'assets/piso1-B.png'],
    ['descartaveis higienicos', 'gondola 123', 'assets/piso1-C.png'],
    ['desinfetante para frutas', 'gondola 123', 'assets/piso1-D.png'],
    ['desinfetantes', 'gondola 123', 'assets/piso1-E.png'],
    ['desodorantes', 'gondola 123', 'assets/piso1-A.png'],
    ['detergentes em po', 'gondola 123', 'assets/piso1-B.png'],
    ['detergentes liquidos', 'gondola 123', 'assets/piso1-C.png'],
    ['dianteiro bovino', 'gondola 123', 'assets/piso1-D.png'],
    ['diet e light', 'gondola 123', 'assets/piso1-E.png'],
    ['doces a granel' 'gondola 123', 'assets/piso1-A.png']
  ],
  '2': [
    ['doces e geleias', 'prateleira xpto', 'assets/piso1-A.png'],
    ['eletrodomesticos', 'prateleira xpto', 'assets/piso2-B.png'],
    ['embalagens', 'prateleira xpto', 'assets/piso2-C.png'],
    ['embutidos', 'prateleira xpto', 'assets/piso2-D.png'],
    ['energeticos e isotonicos', 'prateleira xpto', 'assets/piso2-E.png'],
    ['equipamentos', 'prateleira xpto', 'assets/piso1-A.png'],
    ['especiarias e ervas', 'prateleira xpto', 'assets/piso2-B.png'],
    ['fardamento', 'prateleira xpto', 'assets/piso2-C.png'],
    ['farinaceos e pequenos cereais', 'prateleira xpto', 'assets/piso2-D.png'],
    ['farinha de mandioca', 'prateleira xpto', 'assets/piso2-E.png'],
    ['farinha de trigo', 'prateleira xpto', 'assets/piso1-A.png'],
    ['fatiados', 'prateleira xpto', 'assets/piso2-B.png'],
    ['feijao', 'prateleira xpto', 'assets/piso2-C.png'],
    ['feijao verde', 'prateleira xpto', 'assets/piso2-D.png'],
    ['feirinha', 'prateleira xpto', 'assets/piso2-E.png'],
    ['ferragens e autopecas', 'prateleira xpto', 'assets/piso1-A.png'],
    ['folhagens', 'prateleira xpto', 'assets/piso2-B.png'],
    ['food service', 'prateleira xpto', 'assets/piso2-C.png'],
    ['formados congelados', 'prateleira xpto', 'assets/piso2-D.png'],
    ['frutas', 'prateleira xpto', 'assets/piso2-E.png'],
    ['frutas secas', 'prateleira xpto', 'assets/piso1-A.png'],
    ['gas a granel', 'prateleira xpto', 'assets/piso2-B.png'],
    ['gazes e ataduras', 'prateleira xpto', 'assets/piso2-C.png'],
    ['geleias, pates e molhos', 'prateleira xpto', 'assets/piso2-D.png'],
    ['goma', 'prateleira xpto', 'assets/piso2-E.png'],
    ['grangeiro', 'prateleira xpto', 'assets/piso1-A.png'],
    ['higiene oral', 'prateleira xpto', 'assets/piso2-B.png'],
    ['imobilizado', 'prateleira xpto', 'assets/piso2-C.png'],
    ['inseticidas e repelentes', 'prateleira xpto', 'assets/piso2-D.png'],
    ['insumos', 'prateleira xpto', 'assets/piso2-E.png'],
    ['insumos fornecedores', 'prateleira xpto', 'assets/piso1-A.png'],
    ['insumos padaria', 'prateleira xpto', 'assets/piso2-B.png'],
    ['iogurtes', 'prateleira xpto', 'assets/piso2-C.png'],
    ['jardinagem', 'prateleira xpto', 'assets/piso2-D.png'],
    ['lampadas', 'prateleira xpto', 'assets/piso2-E.png'],
    ['las e palhas de aco', 'prateleira xpto', 'assets/piso1-A.png'],
    ['lava roupas liquido', 'prateleira xpto', 'assets/piso2-B.png'],
    ['legumes', 'prateleira xpto', 'assets/piso2-C.png'],
    ['leite condensado', 'prateleira xpto', 'assets/piso2-D.png'],
    ['leite de coco', 'prateleira xpto', 'assets/piso2-E.png'],
    ['leite e bebida lactea', 'prateleira xpto', 'assets/piso1-A.png'],
    ['leite em po', 'prateleira xpto', 'assets/piso2-B.png'],
    ['leites aromatizados', 'prateleira xpto', 'assets/piso2-C.png'],
    ['leites e derivados', 'prateleira xpto', 'assets/piso2-D.png'],
    ['licores', 'prateleira xpto', 'assets/piso2-E.png'],
    ['limpadores', 'prateleira xpto', 'assets/piso1-A.png'],
    ['linha corporal', 'prateleira xpto', 'assets/piso2-B.png'],
    ['linha facial', 'prateleira xpto', 'assets/piso2-C.png'],
    ['linha p/ maos', 'prateleira xpto', 'assets/piso2-D.png'],
    ['livre', 'prateleira xpto', 'assets/piso2-E.png'],
    ['mant/marg/cr.veg', 'prateleira xpto', 'assets/piso1-A.png'],
    ['maquilagem p/ boca', 'prateleira xpto', 'assets/piso2-B.png'],
    ['maquilagem p/ olhos', 'prateleira xpto', 'assets/piso2-C.png'],
    ['maquilagem p/ rosto', 'prateleira xpto', 'assets/piso2-D.png'],
    ['massas alimenticias', 'prateleira xpto', 'assets/piso2-E.png'],
    ['massas frescas', 'prateleira xpto', 'assets/piso1-A.png'],
    ['mat.expediente / manutencao', 'prateleira xpto', 'assets/piso2-B.png'],
    ['material eletrico', 'prateleira xpto', 'assets/piso2-C.png'],
    ['material eletronico', 'prateleira xpto', 'assets/piso2-D.png'],
    ['matinais', 'prateleira xpto', 'assets/piso2-E.png'],
    ['mix de produtos forn biofit', 'prateleira xpto', 'assets/piso1-A.png'],
    ['moluscos/crustaceos diversos', 'prateleira xpto', 'assets/piso2-B.png'],
    ['nao utilizar', 'prateleira xpto', 'assets/piso2-C.png'],
    ['natalinos', 'prateleira xpto', 'assets/piso2-D.png'],
    ['oleaginosas', 'prateleira xpto', 'assets/piso2-E.png'],
    ['oleos', 'prateleira xpto', 'assets/piso1-A.png'],
    ['outros cortes bovinos', 'prateleira xpto', 'assets/piso2-B.png'],
    ['padaria de terceiros', 'prateleira xpto', 'assets/piso2-C.png'],
    ['panelas/utensilios p/ cozinha', 'prateleira xpto', 'assets/piso2-D.png'],
    ['pao vegano', 'prateleira xpto', 'assets/piso2-E.png'],
    ['papelao/plastico/sucata', 'prateleira xpto', 'assets/piso1-A.png'],
    ['papelaria', 'prateleira xpto', 'assets/piso2-B.png'],
    ['passa roupas', 'prateleira xpto', 'assets/piso2-C.png'],
    ['pecas intimas/meias', 'prateleira xpto', 'assets/piso2-D.png'],
    ['peixes congelados', 'prateleira xpto', 'assets/piso2-E.png'],
    ['peixes enlatados' 'prateleira xpto', 'assets/piso1-A.png']
  ],
  '3': [
    ['peixes frescos', 'lugar xyz', 'assets/piso1-A.png'],
    ['pilhas', 'lugar xyz', 'assets/piso2-B.png'],
    ['pratos prontos congelados', 'lugar xyz', 'assets/piso2-C.png'],
    ['prod automotivos', 'lugar xyz', 'assets/piso2-D.png'],
    ['prod.temporario', 'lugar xyz', 'assets/piso2-E.png'],
    ['producao propria', 'lugar xyz', 'assets/piso1-A.png'],
    ['produto automotivos', 'lugar xyz', 'assets/piso2-B.png'],
    ['produtos capilares', 'lugar xyz', 'assets/piso2-C.png'],
    ['produtos de informatica', 'lugar xyz', 'assets/piso2-D.png'],
    ['produtos farmaceuticos', 'lugar xyz', 'assets/piso2-E.png'],
    ['produtos infantis', 'lugar xyz', 'assets/piso1-A.png'],
    ['produtos natalinos', 'lugar xyz', 'assets/piso2-B.png'],
    ['produtos naturais', 'lugar xyz', 'assets/piso2-C.png'],
    ['produtos organicos', 'lugar xyz', 'assets/piso2-D.png'],
    ['produtos p/ barbear', 'lugar xyz', 'assets/piso2-E.png'],
    ['produtos sazonais', 'lugar xyz', 'assets/piso1-A.png'],
    ['produtos solar', 'lugar xyz', 'assets/piso2-B.png'],
    ['protetor facial', 'lugar xyz', 'assets/piso2-C.png'],
    ['purificadores e desodorantes', 'lugar xyz', 'assets/piso2-D.png'],
    ['queijos', 'lugar xyz', 'assets/piso2-E.png'],
    ['refeicao colaborador', 'lugar xyz', 'assets/piso1-A.png'],
    ['refrigerantes', 'lugar xyz', 'assets/piso2-B.png'],
    ['requeijao', 'lugar xyz', 'assets/piso2-C.png'],
    ['revistas/jornais', 'lugar xyz', 'assets/piso2-D.png'],
    ['rum', 'lugar xyz', 'assets/piso2-E.png'],
    ['sabao barra e sabao pasta', 'lugar xyz', 'assets/piso1-A.png'],
    ['sabonetes e esponjas', 'lugar xyz', 'assets/piso2-B.png'],
    ['sacola' 'lugar xyz', 'assets/piso2-C.png']
  ],
  '4': [
    ['serv.bom vizinho', 'geladeira 456', 'assets/piso1-A.png'],
    ['serv.outros negocios', 'geladeira 456', 'assets/piso2-B.png'],
    ['servicos', 'geladeira 456', 'assets/piso2-C.png'],
    ['shampoos', 'geladeira 456', 'assets/piso2-D.png'],
    ['sobremesas e confeitaria', 'geladeira 456', 'assets/piso2-E.png'],
    ['som e imagem', 'geladeira 456', 'assets/piso1-A.png'],
    ['sopas e caldos', 'geladeira 456', 'assets/piso2-B.png'],
    ['sorvetes e gelo', 'geladeira 456', 'assets/piso2-C.png'],
    ['sucos', 'geladeira 456', 'assets/piso2-D.png'],
    ['suinos', 'geladeira 456', 'assets/piso2-E.png'],
    ['suinos e caprinos', 'geladeira 456', 'assets/piso1-A.png'],
    ['suplemento alimentar', 'geladeira 456', 'assets/piso1-B.png'],
    ['talcos', 'geladeira 456', 'assets/piso1-C.png'],
    ['tequilas', 'geladeira 456', 'assets/piso1-D.png'],
    ['tinta p/tingimento', 'geladeira 456', 'assets/piso1-E.png'],
    ['torrada e bolinhos', 'geladeira 456', 'assets/piso1-A.png'],
    ['toucador', 'geladeira 456', 'assets/piso1-B.png'],
    ['traseiro bovino', 'geladeira 456', 'assets/piso1-C.png'],
    ['tuberculos', 'geladeira 456', 'assets/piso1-D.png'],
    ['uso interno', 'geladeira 456', 'assets/piso1-E.png'],
    ['utensilios de limpeza', 'geladeira 456', 'assets/piso1-A.png'],
    ['vegetais', 'geladeira 456', 'assets/piso1-B.png'],
    ['vegetais enlatados', 'geladeira 456', 'assets/piso1-C.png'],
    ['vermouth', 'geladeira 456', 'assets/piso1-D.png'],
    ['vinagres', 'geladeira 456', 'assets/piso1-E.png'],
    ['vinhos', 'geladeira 456', 'assets/piso1-A.png'],
    ['visceras bovinas', 'geladeira 456', 'assets/piso1-B.png'],
    ['vodkas', 'geladeira 456', 'assets/piso1-C.png'],
    ['whisky' 'geladeira 456', 'assets/piso1-D.png']
  ],
};

List history = [];
